module.exports = lng = [
    {"name": "afrikaans", "abrv":"af"},
    {"name": "albanian", "abrv": "sq", },
    {"name": "arabic","abrv": "ar",},
    {"name": "armenian","abrv": "hy"},
    {"name": "azerbaijani","abrv": "az"},
    {"name": "basque","abrv": "eu"},
    {"name": "belarusian","abrv": " be"},
    {"name": "bengali","abrv": "bn",},
    {"name": "bosnian","abrv": "bs",},
    {"name": "bulgarian","abrv": "bg",},
    {"name": "chinese (simplified)", "abrv": "zh-cn",},
    {"name": "chinese (traditional)", "abrv": "zh-tw",},
    {"name": "catalan","abrv": "ca",},
    {"name": "cebuano","abrv": "ceb",},
    {"name": "chichewa","abrv": "ny",},
    {"name": "corsican","abrv": "co",},
    {"name": "croatian", "abrv": "hr",},
    {"name": "czech", "abrv": "cs"},
    {"name": "danish", "abrv": "da",},
    {"name": "dutch", "abrv": "nl",},
    {"name": "english", "abrv": "en",},
    {"name": "esperanto", "abrv": "eo",},
    {"name": "estonian", "abrv": "et",},
    {"name": "filipino", "abrv": "tl",},
    {"name": "finnish","abrv": "fi",},
    {"name": "french", "abrv": "fr", },
    {"name": "frisian", "abrv": "fy", },
    {"name": "galician", "abrv": "gl", },
    {"name": "georgian", "abrv": "ka", },
    {"name": "german", "abrv": "de",},
    {"name": "greek", "abrv": "el",},
    {"name": "gujarati", "abrv": "gu",},
    {"name": "haitian", "abrv": "ht",},
    {"name": "hausa", "abrv": "ha",},
    {"name": "hebrew","abrv": "iw",},
    {"name": "hindi","abrv": "hi",},
    {"name": "hungarian", "abrv": "hu", },
    {"name": "icelandic", "abrv": "is", },
    {"name": "igbo", "abrv": "ig", },
    {"name": "indonesian", "abrv": "id", },
    {"name": "irish", "abrv": "ga", },
    {"name": "italian", "abrv": "it", },
    {"name": "japanese", "abrv": "ja", },
    {"name": "korean", "abrv": "ko",},
    {"name": "kurdish", "abrv": "ku",},
    {"name": "lao", "abrv": "lo",},
    {"name": "latin", "abrv": "la",},
    {"name": "malay", "abrv": "ms",},
    {"name": "mongolian", "abrv": "mn",},
    {"name": "nepali", "abrv": "ne",},
    {"name":  "norwegian", "abrv": "no",},
    {"name": "persian", "abrv": "fa",},
    {"name":  "polish", "abrv": "pl", },
    {"name": "portuguese", "abrv": "pt",},
    {"name": "punjabi", "abrv": "pa",},
    {"name": "romanian", "abrv": "ro",},
    {"name": "russian", "abrv": "ru",},
    {"name": "serbian", "abrv": "sr",},
    {"name": "spanish", "abrv": "es", },
    {"name": "swahili", "abrv": "sw",},
    {"name": "swedish", "abrv": "sv", },
    {"name": "thai", "abrv": "th", },
    {"name": "turkish", "abrv": "tr", },
    {"name": "ukrainian", "abrv": "uk",},
    {"name": "vietnamese","abrv": "vi", },
    {"name": "welsh", "abrv": "cy",},
    {"name": "yiddish", "abrv": "yi", },
    {"name": "zulu", "abrv": "zu", },

]

